<a href="https://colab.research.google.com/github/shznjihye/Learning/blob/main/lotto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

In [ ]:
font_list = fm.findSystemFonts(fontpaths= None, fontext= 'ttf')
font_list

plt.rc('font', family='LiberationMono-Bold')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ad111.csv', low_memory = False)
df.head()

# low_memory = True는 모든 데이터타입을 일일히 확인 / False는 하나로 통합

num        date     A     B     C     D     E     F     G
0  262.0  2007-12-08  31.0  12.0  25.0  24.0   9.0  29.0  36.0
1  263.0  2007-12-15   1.0  32.0  40.0  37.0  28.0  27.0  18.0
2  264.0  2007-12-22  16.0  36.0   9.0  41.0  44.0  27.0   5.0
3  265.0  2007-12-29   5.0  38.0  39.0  37.0   9.0  34.0  12.0
4  266.0  2008-01-05  42.0   3.0  11.0  22.0   4.0   9.0  37.0

In [ ]:
data1 = df[["num"]]
data1

num
0    262.0
1    263.0
2    264.0
3    265.0
4    266.0
..     ...
816    NaN
817    NaN
818    NaN
819    NaN
820    NaN

[821 rows x 1 columns]

In [ ]:
lottoa = df['A'].dropna().values.tolist()
lottoa

[31.0,
 1.0,
 16.0,
 5.0,
 42.0,
 41.0,
 24.0,
 43.0,
 12.0,
 40.0,
 12.0,
 24.0,
 35.0,
 40.0,
 39.0,
 12.0,
 37.0,
 38.0,
 37.0,
 3.0,
 5.0,
 31.0,
 7.0,
 41.0,
 19.0,
 24.0,
 35.0,
 3.0,
 39.0,
 20.0,
 34.0,
 33.0,
 10.0,
 38.0,
 15.0,
 19.0,
 5.0,
 25.0,
 9.0,
 13.0,
 19.0,
 17.0,
 26.0,
 18.0,
 4.0,
 25.0,
 17.0,
 2.0,
 19.0,
 27.0,
 2.0,
 35.0,
 15.0,
 1.0,
 11.0,
 11.0,
 19.0,
 42.0,
 16.0,
 34.0,
 38.0,
 32.0,
 25.0,
 45.0,
 33.0,
 12.0,
 1.0,
 9.0,
 3.0,
 4.0,
 45.0,
 43.0,
 21.0,
 9.0,
 5.0,
 37.0,
 13.0,
 21.0,
 26.0,
 39.0,
 33.0,
 31.0,
 15.0,
 23.0,
 14.0,
 32.0,
 14.0,
 5.0,
 33.0,
 27.0,
 17.0,
 36.0,
 45.0,
 35.0,
 8.0,
 37.0,
 21.0,
 20.0,
 25.0,
 24.0,
 30.0,
 21.0,
 2.0,
 30.0,
 19.0,
 25.0,
 24.0,
 41.0,
 45.0,
 7.0,
 8.0,
 45.0,
 11.0,
 27.0,
 40.0,
 22.0,
 29.0,
 35.0,
 37.0,
 5.0,
 15.0,
 15.0,
 32.0,
 7.0,
 7.0,
 40.0,
 29.0,
 26.0,
 16.0,
 11.0,
 8.0,
 43.0,
 20.0,
 35.0,
 18.0,
 25.0,
 44.0,
 9.0,
 34.0,
 18.0,
 36.0,
 28.0,
 40.0,
 26.0,
 12.0,
 24.0,
 20.0,

In [ ]:
import numpy as np
lotto_a, a_number = np.unique(lottoa, return_counts=True)

In [ ]:
lotto_a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45.])

In [ ]:
a_number

array([19, 16, 14, 20, 17,  7, 16, 18, 11,  9, 17, 20, 17, 17, 16, 13,  9,
       15, 15, 18, 17, 10, 19, 15, 17, 20, 16, 11, 12, 11, 12, 16, 13, 19,
       16, 16, 22,  7, 17, 20, 15, 17, 14, 17, 24])

In [ ]:
lotto_b, b_number = np.unique(df['B'].dropna().values.tolist(), return_counts=True)
lotto_c, c_number = np.unique(df['C'].dropna().values.tolist(), return_counts=True)
lotto_d, d_number = np.unique(df['D'].dropna().values.tolist(), return_counts=True)
lotto_e, e_number = np.unique(df['E'].dropna().values.tolist(), return_counts=True)
lotto_f, f_number = np.unique(df['F'].dropna().values.tolist(), return_counts=True)

In [13]:
lotto_s = a_number + b_number + c_number + d_number + e_number + f_number

In [14]:
lotto_s

array([ 97,  85,  88,  91,  93,  84,  90,  97,  78,  99,  92, 111, 102,
        97,  98,  93, 102, 101,  91,  97,  91,  84,  83,  92,  84,  90,
       105,  92,  85,  83,  95,  81,  97, 110,  80,  86,  85, 102, 100,
        97,  89,  86, 108,  92,  99])

동행복권 사이트 가보니까 수치 안맞음.........
데이터가 잘못된 것 같다 ,,

#실패!!